name: GHA mainワークフロー

on:
  workflow_dispatch:
    inputs:
      passed:
        type: boolean
        required: true
        default: false
        description: 'true: subワークフローを実行しない, false: subワークフローを実行する'
      message:
        type: string
        required: true
        default: 'Error: timeout'
        description: 'subワークフローに渡すメッセージ'

env:
  GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER
  GITHUB_TARGET_REPOSITORY: hello-gha-sub

jobs:
  gha-main:
    runs-on: ubuntu-latest
    steps:
      - name: GHA mainワークフローを開始
        run: |
          echo "main started."
      - name: GHA subワークフローを呼び出し
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.GITHUB_REPOSITORY_OWNER }}/${{ env.GITHUB_TARGET_REPOSITORY }}/dispatches \
            -d '{"event_type":"test_result","client_payload":{"passed":$passed,"message":$message}}'
      - name: GHA mainワークフローを終了
        run: |
          echo "main ended."
