name: GHA mainワークフロー

on:
  workflow_dispatch:
    inputs:
      env:
        description: "環境を選んでください。"
        type: choice
        options:
          - prd
          - stg
          - dev

env:
  GITHUB_TARGET_REPOSITORY: hello-gha-sub

jobs:
  gha-main:
    runs-on: ubuntu-latest
    steps:
      - name: GHA mainワークフローを開始
        run: |
          echo "main started."
      - name: GHA subワークフローを呼び出し
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ env.GITHUB_TARGET_REPOSITORY }}/dispatches \
            -d '{"event_type":"test_result","client_payload":{"passed":false,"message":"Error: timeout","env":${{ inputs.env }}}}'
      - name: GHA mainワークフローを終了
        run: |
          echo "main ended."
