name: GHA mainワークフロー

on:
  workflow_dispatch:
    inputs:
      env:
        description: "環境を選んでください。"
        type: choice
        options:
          - prd
          - stg
          - dev

env:
  GITHUB_TARGET_REPOSITORY: hello-gha-sub

jobs:
  gha-main:
    runs-on: ubuntu-latest
    steps:
      - name: GHA mainワークフローを開始
        run: |
          echo "main started."
      - name: GHA subワークフローを呼び出し
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ env.GITHUB_TARGET_REPOSITORY }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: sub.yml
          propagate_failure: true
          ref: ${{ github.base_ref || github.ref_name }}
          client_payload: '{"event_type":"test_result","client_payload":{"passed":false,"message":"Error: timeout","env":"${{ inputs.env }}"}}'
      - name: GHA mainワークフローを終了
        run: |
          echo "main ended."
